trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# ------------------------------------
# Checkout the repo
# ------------------------------------
- checkout: self
  fetchDepth: 0

# ------------------------------------
# Install .NET 8 SDK (optional, ensures correct version)
# ------------------------------------
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

# ------------------------------------
# SonarCloud Prepare
# ------------------------------------
- task: SonarCloudPrepare@3
  inputs:
    SonarQube: 'azure-devops'                 # Your service connection name
    organization: 'vaishnavira-cybage'       # SonarCloud org key (NO spaces)
    scannerMode: 'dotnet'
    projectKey: 'vaishnavira-cybage_SonarCloudDemo'
    projectName: 'SonarCloudDemo'
    extraProperties: |
      sonar.scanner.scanAll=false
      # Must match Coverlet output file
      sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/SonarCloud/Tests/results/coverage.opencover.xml

# ------------------------------------
# Build the solution
# ------------------------------------
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'SonarCloud/SonarCloudDemo.sln'
    arguments: '--configuration Release'

# ------------------------------------
# Run tests + generate coverage
# ------------------------------------
- task: DotNetCoreCLI@2
  displayName: 'Run Tests with Coverage'
  inputs:
    command: 'test'
    projects: 'SonarCloud/Tests/Tests.csproj'
    arguments: >
      --configuration Release
      /p:CollectCoverage=true
      /p:CoverletOutput=$(Build.SourcesDirectory)/SonarCloud/Tests/results/coverage.opencover.xml
      /p:CoverletOutputFormat=opencover
    publishTestResults: true

# ------------------------------------
# SonarCloud Analyze
# ------------------------------------
- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

# ------------------------------------
# SonarCloud Publish
# ------------------------------------
- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'

# ------------------------------------
# Publish coverage to Azure DevOps
# ------------------------------------
- task: PublishCodeCoverageResults@2
  displayName: 'Publish Code Coverage Results'
  inputs:
    summaryFile: '$(Build.SourcesDirectory)/SonarCloud/Tests/results/coverage.opencover.xml'
    reportDirectory: '$(Build.SourcesDirectory)/SonarCloud/Tests/results'
    failIfCoverageEmpty: true
