trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# ------------------------------------
# Checkout
# ------------------------------------
- checkout: self
  fetchDepth: 0

# ------------------------------------
# SonarCloud Prepare
# ------------------------------------
- task: SonarCloudPrepare@3
  inputs:
    SonarQube: 'azure-devops'                 # Azure DevOps service connection name
    organization: 'vaishnavira-cybage'      # SonarCloud org key (NO spaces)
    scannerMode: 'dotnet'
    projectKey: 'vaishnavira-cybage_SonarCloudDemo'
    projectName: 'SonarCloudDemo'
    extraProperties: |
      sonar.scanner.scanAll=false
      sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/SonarCloud/Tests/results/coverage.opencover.xml

# ------------------------------------
# Build
# ------------------------------------
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'SonarCloud/SonarCloudDemo.sln'
    arguments: '--configuration Release'

# ------------------------------------
# Test + Coverage
# ------------------------------------
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'SonarCloud/Tests/Tests.csproj'
    arguments: '--configuration Release'
    publishTestResults: true

# ------------------------------------
# SonarCloud Analyze
# ------------------------------------
- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

# ------------------------------------
# SonarCloud Publish
# ------------------------------------
- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'

# ------------------------------------
# Publish Coverage to Azure DevOps
# ------------------------------------
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/SonarCloud/Tests/results/coverage.cobertura.xml'
    failIfCoverageEmpty: true
